classOrder = [
    "PlugDefinition",
    "PlugField",
    "SocketSettings",
]

[docusaurus]
tagline = "A Macro Manager Plugin for Roblox"
favicon = "/square_logo_512.png"

[home]
enabled = true

[[navbar.items]]
href = "https://www.roblox.com/library/9988470603/Socket"
label = "Roblox"
position = "right"

[[home.features]]
title = "Customisable"
description = "There are many ways to customise the plugin to make it fit your personal taste and accessibilty requirements"

[[home.features]]
title = "Easy collaboration"
description = "It's easy to share macros among your team, be it through Team Create or Rojo"

[[home.features]]
title = "Modern"
description = "This is probably the most powerful macro manager for Roblox (and uses Roact + Rodux!)"