[docusaurus]
tagline = "A Macro Manager Plugin for Roblox"
favicon = "/square_logo.png"

[home]
enabled = true

[[navbar.items]]
href = "https://www.roblox.com/users/16290995/profile"
label = "Roblox"
position = "right"

[[home.features]]
title = "Customisable"
description = "There are lots of ways to customise the plugin to make it fit your personal taste and accessibilty requirements"

[[home.features]]
title = "Easy collaboration"
description = "It's super simple to share macros among your team, be it through Roblox Studio or Rojo syncing"

[[home.features]]
title = "Modern"
description = "This is probably the most powerful macro manager for Roblox (and it uses Roact & Rodux!)"